[plotly-artifacts]
git-tree-sha1 = "bc8e1450d988edc838c4f4bbe03439b715c6215f"

    [[plotly-artifacts.download]]
    sha256 = "8d0799af112772a95b6490f763cf505128dd83be8f59e13aa27378a92f7d5a38"
    url = "https://github.com/JuliaPlots/PlotlyJS.jl/releases/download/plotly-artifacts-2.2.1/plotly-artifacts-2.2.1.tar.gz"
