[plotly-artifacts]
git-tree-sha1 = "4fa45e1c116c49318fa3d60adb843b5db5c13069"

    [[plotly-artifacts.download]]
    url = "https://api.plot.ly/v2/plot-schema?sha1"
    
    [[plotly-artifacts.download]]
    url = "https://cdn.plot.ly/plotly-latest.min.js"
