[plotly-artifacts]
git-tree-sha1 = "4fa45e1c116c49318fa3d60adb843b5db5c13069"

    [[plotly-artifacts.download]]
    sha256 = "dfdbcfb16516b339645cc83e493dd303c3e5fea600a55856e7d81907bff80a98"
    url = "https://github.com/jonas-kr/PlotlyJS.jl/releases/download/plotly-artifacts/plotly-artifacts-1.58.4.tar.gz"
