[plotly-artifacts]
git-tree-sha1 = "94b18606d21e46687da7e86f1f63afbfa09ce3fb"

    [[plotly-artifacts.download]]
    sha256 = "1ca88ece3011889d182885a6a0d6de9439cae5716fd0ea70d3fc711f8e61fd7a"
    url = "https://github.com/JuliaPlots/PlotlyJS.jl/releases/download/plotly-artifacts-1.58.4/plotly-artifacts-1.58.4.tar.gz"
